# Generated by Django 4.2.6 on 2023-11-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
