# Generated by Django 4.2.6 on 2023-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='books',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='exampaper',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='material',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='newspaper',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='pen',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
